config/routes.rb
Vigu::Application.routes.draw do

  scope "(:locale)", :locale => /de|en|es/ do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :paragraphs

    resources :translations

    namespace :admin do
      resources :news do
        collection do
          post :sort
        end
      end

      resources :partners do
        collection do
          post :sort
        end
      end

      match 'about',              to: 'about#edit'
      match 'about/update',       to: 'about#update'

      match 'home',              to: 'home#edit'
      match 'home/update',       to: 'home#update'
      match '/',               to: 'home#edit'
      match '/home/sort',               to: 'home#sort', :via => :post

      match 'switch_to_admin_view',        to: 'application#switch_to_admin_view'
      match 'switch_to_normal_view',        to: 'application#switch_to_normal_view'
    end

    root to: "home#show"

    match 'news',               to: 'news#index'
    match 'partners',               to: 'partners#index'
    match 'about',               to: 'about#show'
    match 'home',               to: 'home#show'

    match '/register',          to: 'users#new'
    match '/login',             to: 'sessions#new'
    match '/logout',            to: 'sessions#destroy', via: :delete

    match 'development/roadmap', to: 'development#roadmap'
    match 'development/todo',    to: 'development#todo'
    match 'development/done',    to: 'development#done'
  end

end

app/controllers/admin/partners_controller.rb
class Admin::PartnersController < Admin::SingleParagraphPageController

  def initialize
    @page = Page.find_by_name(:partners)
    super
  end

  def new
    paragraph = super
    redirect_to edit_admin_partner_path(paragraph)
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController

  def index
    @page = Page.find_by_name('partners')
  end

end

app/views/admin/partners/edit.html.haml
- provide(:title, admin_title(t(:partners)))
- provide(:normal_view_link, partners_path)

%h1= "Partners:"
= form_for @paragraph, :url => admin_partner_path(@paragraph), :html => { :multipart => true } do |f|
  = paragraph_form(f)
  = f.submit(t(:save))

app/views/admin/partners/index.html.haml
- provide(:title, t(:partners).capitalize)
- provide(:normal_view_link, partners_path)

%ul{:id => "paragraphs", "data-update-url" => sort_admin_partners_url}
  - @page.get_paragraphs(:main).order(:position).each do |paragraph|
    - @paragraph = paragraph
    = content_tag_for :li, @paragraph do
      .paragraph_overview
        = link_to(edit_admin_partner_path(@paragraph)) do
          = render_partial(:paragraph_overview)
          %br
          = link_to image_tag("trash.png", :width => 50), @paragraph, :method => :delete

%br
= link_to("#{t(:paragraph)} #{t(:add)}", new_admin_partner_path)