config/routes.rb
Vigu::Application.routes.draw do

  scope "(:locale)", :locale => /de|en|es/ do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :paragraphs

    resources :translations

    namespace :admin do
      resources :news do
        collection do
          post :sort
        end
      end

      resources :partners do
        collection do
          post :sort
        end
      end

      match 'about',              to: 'about#edit'
      match 'about/update',       to: 'about#update'

      match 'home',              to: 'home#edit'
      match 'home/update',       to: 'home#update'
      match '/',               to: 'home#edit'
      match '/home/sort',               to: 'home#sort', :via => :post

      match 'switch_to_admin_view',        to: 'application#switch_to_admin_view'
      match 'switch_to_normal_view',        to: 'application#switch_to_normal_view'
    end

    root to: "home#show"

    match 'news',               to: 'news#index'
    match 'partners',               to: 'partners#index'
    match 'about',               to: 'about#show'
    match 'home',               to: 'home#show'

    match '/register',          to: 'users#new'
    match '/login',             to: 'sessions#new'
    match '/logout',            to: 'sessions#destroy', via: :delete

    match 'development/roadmap', to: 'development#roadmap'
    match 'development/todo',    to: 'development#todo'
    match 'development/done',    to: 'development#done'
  end

end

app/models/home.rb
class Home < Page
  include ApplicationHelper

  attr_accessible :page_title, :people_title, :work_title,
                  :contact_title, :contact_email_address
  attr_accessor :page_title, :people_title, :work_title,
                :contact_title, :contact_email_address

  after_save :update_translation

  def update_translation
    update_translations(I18n.locale, {:home_page_title => page_title})
    update_translations(I18n.locale, {:home_people_title => people_title})
    update_translations(I18n.locale, {:home_work_title => work_title})
    update_translations(I18n.locale, {:home_contact_title => contact_title})
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::MultiParagraphPageController

  def initialize
    @page = Page.find_by_name(:home).becomes(Home)
    @people_collection = @page.get_paragraph_collection(:people)
    @work_collection = @page.get_paragraph_collection(:work)
    super
  end

  def sort
    # result = ""
    params[:paragraph].each_with_index do |id, index|
      # result += "Paragraph(#{id}) new position #{index+1} ; "
      Paragraph.update_all({position: index+1}, {id: id})
    end
    # flash.notice = result
    render nothing: true
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @page = Page.find_by_name(:home)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/home/edit.html.haml
- provide(:title, admin_title(t(:home)))
- provide(:normal_view_link, home_path)

- def get_admin_title_input(text, form)
  - return admin_line_input(symbol="#{text}_title", translation_tag="home_#{text}_title", css_class="input_title", form=form)

- def get_admin_input(text, form)
  - return admin_line_input(symbol=text, translation_tag=text, css_class="input_normal", form=form)


= form_for @page, :url => admin_home_update_path, :html => { :multipart => true, :name => "savable_form" } do |page_builder|

  %table
    = get_admin_title_input("page", page_builder)
    = get_admin_title_input("people", page_builder)

  - @paragraph_collection = @people_collection
  = render_partial(:paragraphs_form, {:form => page_builder})


  %table
    = get_admin_title_input("work", page_builder)

  - @paragraph_collection = @work_collection
  = render_partial(:paragraphs_form, {:form => page_builder})

  %table
    = get_admin_title_input("contact", page_builder)

  %br

  = page_builder.submit t(:save), :name => "save_button"

app/views/admin/home/show.html.haml
- provide(:title, admin_title(t(:home)))
= paragraphs_form(admin_new_paragraph_path, admin_update_path)